package com.example.android_project_cmpe_235;

import android.app.ActionBar;
import android.app.FragmentManager;
import android.app.FragmentTransaction;
import android.os.Bundle;
import android.support.v4.app.FragmentActivity;
import android.support.v4.view.ViewPager;
import android.view.Menu;

public class MainActivity extends FragmentActivity implements CameraFragment.QrResultReturn {

    /**
     * The {@link android.support.v4.view.PagerAdapter} that will provide fragments for each of the
     * sections. We use a {@link android.support.v4.app.FragmentPagerAdapter} derivative, which will
     * keep every loaded fragment in memory. If this becomes too memory intensive, it may be best
     * to switch to a {@link android.support.v4.app.FragmentStatePagerAdapter}.
     */
    /**
     * The {@link ViewPager} that will host the section contents.
     */
    ViewPager mViewPager;
    
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // Create the adapter that will return a fragment for each of the three primary sections
        // of the app.

        // Set up the action bar.
        final ActionBar actionBar = getActionBar();
        FragmentManager fm = getFragmentManager();
        FragmentTransaction ft = fm.beginTransaction();
        
        ft.add(R.id.pager, new CameraFragment());
        ft.commit();


        // When swiping between different sections, select the corresponding tab.
        // We can also use ActionBar.Tab#select() to do this if we have a reference to the
        // Tab.
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.activity_main, menu);
        return true;
    }

    @Override
	public void QrResults(String result) {
		// TODO Auto-generated method stub
		//uses google api to generate qr code
		/*QrURL = "http://chart.googleapis.com/chart?chs=100x100&cht=qr&chl=" + result;
		QrImage.setTag(QrURL);
		//retrive the QR generated by google api
		new ImageDownloader().execute(QrImage);
		textView.setText(result);
		ResultText = result;
		setShareString(ResultText);
		if(result.contains("http://")) { //if link
			ResultIsUrl = true;
			if(result.contains(".mp3")) { //if audio
				IsMedia = 1;
				button.setText("Listen to Audio");
			}
			//if video
			else if(result.contains(".3gp") || result.contains(".ogg") || result.contains(".mp4")) {
				IsMedia = 2;
				button.setText("View Video");
			}
			//if image
			else if(result.contains(".jpg") || result.contains(".png")) {
				IsMedia = 3;
				button.setText("View Image");
			}
			//else open link to browser
			else {
				IsMedia = 4;
				button.setText("Open Link...");
			}
		}
		else {
			ResultIsUrl = false;
			IsMedia = 0;
			button.setText("Waiting for Link...");
		}*/
			
	}
    


}
